from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean
from sqlalchemy.sql import func
from app.database import Base

# Represents an automated alert or recommendation generated by the system
class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    building_id = Column(Integer, ForeignKey("buildings.id"), nullable=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    severity = Column(String, default="Info")  # Added severity
    title = Column(String)
    description = Column(String)
    is_resolved = Column(Boolean, default=False)
