// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JDCURuJXwZMC3VdJ2gedkrn_W6wv1Xc',
    appId: '1:1008549395676:web:704de826bdfa1b11520819',
    messagingSenderId: '1008549395676',
    projectId: 'smart-energy-ai-3ff26',
    authDomain: 'smart-energy-ai-3ff26.firebaseapp.com',
    storageBucket: 'smart-energy-ai-3ff26.firebasestorage.app',
    measurementId: 'G-XWGHW0NW86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YT1CQgAiCIUDMva1TQuq6Db9HNmiLWI',
    appId: '1:1008549395676:android:bef415eda2ba3077520819',
    messagingSenderId: '1008549395676',
    projectId: 'smart-energy-ai-3ff26',
    storageBucket: 'smart-energy-ai-3ff26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyXRHgmApqtev3pL3MoNZaXt-smt1MQk',
    appId: '1:1008549395676:ios:e6e20076c11dd6b1520819',
    messagingSenderId: '1008549395676',
    projectId: 'smart-energy-ai-3ff26',
    storageBucket: 'smart-energy-ai-3ff26.firebasestorage.app',
    iosClientId: '1008549395676-iaai86j84qc496m565d1909mg6n21q9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyXRHgmApqtev3pL3MoNZaXt-smt1MQk',
    appId: '1:1008549395676:ios:e6e20076c11dd6b1520819',
    messagingSenderId: '1008549395676',
    projectId: 'smart-energy-ai-3ff26',
    storageBucket: 'smart-energy-ai-3ff26.firebasestorage.app',
    iosClientId: '1008549395676-iaai86j84qc496m565d1909mg6n21q9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3JDCURuJXwZMC3VdJ2gedkrn_W6wv1Xc',
    appId: '1:1008549395676:web:347d27f626f37f3d520819',
    messagingSenderId: '1008549395676',
    projectId: 'smart-energy-ai-3ff26',
    authDomain: 'smart-energy-ai-3ff26.firebaseapp.com',
    storageBucket: 'smart-energy-ai-3ff26.firebasestorage.app',
    measurementId: 'G-XC1BSXZ5K2',
  );
}
